before_install:
  - cd demo
  - pwd
  - ls -la
  - chmod +x ./gradlew

before deploy:
  - cd ..
  - zip -r communitysite *
  - mkdir -p deploy
  - mv communitysite.zip deploy/communitysite.zip

language: java
jdk:
  - openjdk11

branches:
  only:
    - main

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build -x test"

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: communitysite-deploy
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    local_dir: deploy
    on:
      repo: Jzakka/CommunitySite
      branch: main

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: communitysite-deploy
    key: communitysite.zip
    bundle_type: zip
    application: springboot-web
    deployment_group: springboot-web-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: Jzakka/CommunitySite
      branch: main
  
notifications:
  email:
    recipients:
      - mouse4786@gmail.com 
