spring:
  profiles:
    active: dev

logging.level:
  org.hibernate.SQL: debug

server:
  error:
    include-message: never
    include-stacktrace: never
    include-binding-errors: never
  servlet:
    session:
      tracking-modes: cookie
      timeout: 300
  port: 9090

file:
  dir: /Users/Projects/file/