spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/communitysite
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
  #      show_sql: true
        format_sql: true
        default_batch_fetch_size: 600

logging.level:
  org.hibernate.SQL: debug

server:
  error:
    include-message: never
    include-stacktrace: never
    include-binding-errors: never
  servlet:
    session:
      tracking-modes: cookie
      timeout: 300

file:
  dir: /Users/Projects/file/